use_frameworks!

platform :ios, '8.0'

target 'UIViewSeparatorLine_Example' do
  pod 'UIViewSeparatorLine', :path => '../'

  target 'UIViewSeparatorLine_Tests' do
    inherit! :search_paths

    
  end
end
